/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAnalytics {
  'totalProperties' : bigint,
  'refundsProcessed' : bigint,
  'totalBookings' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'activeStays' : bigint,
  'pendingVerifications' : bigint,
}
export interface AvailabilityResult {
  'available' : boolean,
  'nextAvailableFrom' : [] | [bigint],
}
export interface Booking {
  'id' : bigint,
  'checkIn' : bigint,
  'paymentStatus' : PaymentStatus,
  'decisionDeadline' : bigint,
  'invoiceUrl' : [] | [string],
  'serviceAddons' : Array<ServiceAddon>,
  'createdAt' : bigint,
  'totalDays' : bigint,
  'propertyId' : bigint,
  'decisionStatus' : DecisionStatus,
  'checkOut' : bigint,
  'customerId' : Principal,
  'totalPrice' : bigint,
}
export interface BookingInput {
  'checkIn' : bigint,
  'totalDays' : bigint,
  'propertyId' : bigint,
  'serviceAddonIds' : Array<bigint>,
}
export type DecisionStatus = { 'expired' : null } |
  { 'pending' : null } |
  { 'refunded' : null } |
  { 'accepted' : null };
export type DocType = { 'other' : null } |
  { 'passport' : null } |
  { 'aadhaar' : null } |
  { 'drivingLicense' : null };
export type DocVerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface Document {
  'id' : bigint,
  'bookingId' : bigint,
  'ownerId' : Principal,
  'fileBlob' : ExternalBlob,
  'docType' : DocType,
  'verificationStatus' : DocVerificationStatus,
  'uploadedAt' : bigint,
  'uploadedBy' : UploadedBy,
}
export interface DocumentInput {
  'bookingId' : bigint,
  'fileBlob' : ExternalBlob,
  'docType' : DocType,
  'uploadedBy' : UploadedBy,
}
export type ExternalBlob = Uint8Array;
export type FurnishingType = { 'semiFurnished' : null } |
  { 'furnished' : null } |
  { 'unfurnished' : null };
export interface Location {
  'lat' : number,
  'lng' : number,
  'city' : string,
  'address' : string,
}
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'notificationType' : NotificationType,
  'createdAt' : bigint,
  'read' : boolean,
  'message' : string,
}
export type NotificationType = { 'extendReminder' : null } |
  { 'paymentSuccess' : null } |
  { 'visitReminder' : null } |
  { 'bookingConfirmed' : null } |
  { 'docUploaded' : null } |
  { 'refundProcessed' : null };
export interface OwnerEarnings {
  'activeBookings' : bigint,
  'totalEarned' : bigint,
  'totalBookings' : bigint,
  'pendingPayout' : bigint,
}
export interface Payment {
  'id' : bigint,
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'bookingId' : bigint,
  'createdAt' : bigint,
  'holdReleaseAt' : bigint,
  'amount' : bigint,
}
export interface PaymentInput {
  'paymentMethod' : PaymentMethod,
  'bookingId' : bigint,
  'amount' : bigint,
}
export type PaymentMethod = { 'upi' : null } |
  { 'card' : null } |
  { 'wallet' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'failed' : null };
export interface PendingPayout {
  'bookingId' : bigint,
  'ownerId' : Principal,
  'releaseAt' : bigint,
  'processed' : boolean,
  'amount' : bigint,
}
export interface Property {
  'id' : bigint,
  'status' : PropertyStatus,
  'propertyType' : PropertyType,
  'ownerId' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'amenities' : Array<string>,
  'updatedAt' : bigint,
  'furnishingType' : FurnishingType,
  'tenantType' : TenantType,
  'monthlyRent' : bigint,
  'roomsAvailable' : bigint,
  'verificationNotes' : [] | [string],
  'assignedExecutiveId' : [] | [Principal],
  'perDayPrice' : bigint,
  'location' : Location,
  'photos' : Array<ExternalBlob>,
  'totalRooms' : bigint,
  'maxGuests' : bigint,
}
export interface PropertyFilter {
  'propertyType' : [] | [PropertyType],
  'city' : [] | [string],
  'maxPrice' : [] | [bigint],
  'tenantType' : [] | [TenantType],
  'minPrice' : [] | [bigint],
}
export interface PropertyInput {
  'propertyType' : PropertyType,
  'description' : string,
  'amenities' : Array<string>,
  'furnishingType' : FurnishingType,
  'tenantType' : TenantType,
  'monthlyRent' : bigint,
  'roomsAvailable' : bigint,
  'location' : Location,
  'photos' : Array<ExternalBlob>,
  'totalRooms' : bigint,
  'maxGuests' : bigint,
}
export type PropertyStatus = { 'assigned' : null } |
  { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export type PropertyType = { 'twoBHK' : null } |
  { 'oneRK' : null } |
  { 'room' : null } |
  { 'threeBHK' : null } |
  { 'oneBHK' : null };
export interface Rating {
  'id' : bigint,
  'bookingId' : bigint,
  'createdAt' : bigint,
  'propertyId' : bigint,
  'reviewText' : string,
  'customerId' : Principal,
  'rating' : bigint,
}
export interface RatingInput {
  'bookingId' : bigint,
  'propertyId' : bigint,
  'reviewText' : string,
  'rating' : bigint,
}
export interface Service {
  'id' : bigint,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'category' : ServiceCategory,
  'price' : bigint,
}
export interface ServiceAddon {
  'serviceName' : string,
  'serviceId' : bigint,
  'price' : bigint,
}
export type ServiceCategory = { 'setupKit' : null } |
  { 'other' : null } |
  { 'acCleaning' : null } |
  { 'homeCleaning' : null };
export interface ServiceInput {
  'name' : string,
  'description' : string,
  'category' : ServiceCategory,
  'price' : bigint,
}
export interface TaskInput {
  'bookingId' : [] | [bigint],
  'propertyId' : bigint,
  'executiveId' : Principal,
  'taskType' : TaskType,
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type TaskType = { 'customerCheckin' : null } |
  { 'propertyVerification' : null };
export type TenantType = { 'all' : null } |
  { 'boys' : null } |
  { 'girls' : null } |
  { 'family' : null };
export type UploadedBy = { 'customer' : null } |
  { 'executive' : null };
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
  'blacklisted' : boolean,
  'verificationStatus' : VerificationStatus,
}
export interface UserProfileInput {
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'owner' : null } |
  { 'executive' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'unverified' : null } |
  { 'rejected' : null };
export interface VerificationTask {
  'id' : bigint,
  'status' : TaskStatus,
  'completedAt' : [] | [bigint],
  'bookingId' : [] | [bigint],
  'createdAt' : bigint,
  'propertyId' : bigint,
  'executiveId' : Principal,
  'taskType' : TaskType,
  'notes' : [] | [string],
  'photos' : Array<ExternalBlob>,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approveProperty' : ActorMethod<[bigint, [] | [string]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignExecutive' : ActorMethod<[bigint, Principal], undefined>,
  'blacklistUser' : ActorMethod<[Principal], undefined>,
  'createBooking' : ActorMethod<[BookingInput], Booking>,
  'createDocument' : ActorMethod<[DocumentInput], Document>,
  'createPayment' : ActorMethod<[PaymentInput], Payment>,
  'createProperty' : ActorMethod<[PropertyInput], Property>,
  'createService' : ActorMethod<[ServiceInput], Service>,
  'createVerificationTask' : ActorMethod<[TaskInput], VerificationTask>,
  'getAdminAnalytics' : ActorMethod<[], AdminAnalytics>,
  'getAdminBookings' : ActorMethod<[], Array<Booking>>,
  'getAdminPayments' : ActorMethod<[], Array<Payment>>,
  'getAdminProperties' : ActorMethod<[], Array<Property>>,
  'getAdminUsers' : ActorMethod<[], Array<UserProfile>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getBookingDocuments' : ActorMethod<[bigint], Array<Document>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyPayments' : ActorMethod<[], Array<Payment>>,
  'getMyTasks' : ActorMethod<[], Array<VerificationTask>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getOwnerEarnings' : ActorMethod<[], OwnerEarnings>,
  'getPendingPayouts' : ActorMethod<[], Array<PendingPayout>>,
  'getProperties' : ActorMethod<[[] | [PropertyFilter]], Array<Property>>,
  'getProperty' : ActorMethod<[bigint], [] | [Property]>,
  'getPropertyAvailability' : ActorMethod<
    [bigint, bigint, bigint],
    AvailabilityResult
  >,
  'getPropertyRatings' : ActorMethod<[bigint], Array<Rating>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'markPayoutProcessed' : ActorMethod<[bigint], undefined>,
  'processDecision' : ActorMethod<[bigint, DecisionStatus], Booking>,
  'rejectProperty' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'seedSampleBookings' : ActorMethod<[Principal], undefined>,
  'submitRating' : ActorMethod<[RatingInput], Rating>,
  'updateProperty' : ActorMethod<[bigint, PropertyInput], [] | [Property]>,
  'updateTaskStatus' : ActorMethod<
    [bigint, TaskStatus, [] | [string]],
    VerificationTask
  >,
  'updateUserProfile' : ActorMethod<[UserProfileInput], UserProfile>,
  'uploadVerificationPhoto' : ActorMethod<
    [bigint, ExternalBlob],
    VerificationTask
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];