/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingInput = IDL.Record({
  'checkIn' : IDL.Int,
  'totalDays' : IDL.Nat,
  'propertyId' : IDL.Nat,
  'serviceAddonIds' : IDL.Vec(IDL.Nat),
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const ServiceAddon = IDL.Record({
  'serviceName' : IDL.Text,
  'serviceId' : IDL.Nat,
  'price' : IDL.Nat,
});
export const DecisionStatus = IDL.Variant({
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'refunded' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'checkIn' : IDL.Int,
  'paymentStatus' : PaymentStatus,
  'decisionDeadline' : IDL.Int,
  'invoiceUrl' : IDL.Opt(IDL.Text),
  'serviceAddons' : IDL.Vec(ServiceAddon),
  'createdAt' : IDL.Int,
  'totalDays' : IDL.Nat,
  'propertyId' : IDL.Nat,
  'decisionStatus' : DecisionStatus,
  'checkOut' : IDL.Int,
  'customerId' : IDL.Principal,
  'totalPrice' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocType = IDL.Variant({
  'other' : IDL.Null,
  'passport' : IDL.Null,
  'aadhaar' : IDL.Null,
  'drivingLicense' : IDL.Null,
});
export const UploadedBy = IDL.Variant({
  'customer' : IDL.Null,
  'executive' : IDL.Null,
});
export const DocumentInput = IDL.Record({
  'bookingId' : IDL.Nat,
  'fileBlob' : ExternalBlob,
  'docType' : DocType,
  'uploadedBy' : UploadedBy,
});
export const DocVerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'fileBlob' : ExternalBlob,
  'docType' : DocType,
  'verificationStatus' : DocVerificationStatus,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : UploadedBy,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'card' : IDL.Null,
  'wallet' : IDL.Null,
});
export const PaymentInput = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'bookingId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'bookingId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'holdReleaseAt' : IDL.Int,
  'amount' : IDL.Nat,
});
export const PropertyType = IDL.Variant({
  'twoBHK' : IDL.Null,
  'oneRK' : IDL.Null,
  'room' : IDL.Null,
  'threeBHK' : IDL.Null,
  'oneBHK' : IDL.Null,
});
export const FurnishingType = IDL.Variant({
  'semiFurnished' : IDL.Null,
  'furnished' : IDL.Null,
  'unfurnished' : IDL.Null,
});
export const TenantType = IDL.Variant({
  'all' : IDL.Null,
  'boys' : IDL.Null,
  'girls' : IDL.Null,
  'family' : IDL.Null,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'city' : IDL.Text,
  'address' : IDL.Text,
});
export const PropertyInput = IDL.Record({
  'propertyType' : PropertyType,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'furnishingType' : FurnishingType,
  'tenantType' : TenantType,
  'monthlyRent' : IDL.Nat,
  'roomsAvailable' : IDL.Nat,
  'location' : Location,
  'photos' : IDL.Vec(ExternalBlob),
  'totalRooms' : IDL.Nat,
  'maxGuests' : IDL.Nat,
});
export const PropertyStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : PropertyStatus,
  'propertyType' : PropertyType,
  'ownerId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
  'furnishingType' : FurnishingType,
  'tenantType' : TenantType,
  'monthlyRent' : IDL.Nat,
  'roomsAvailable' : IDL.Nat,
  'verificationNotes' : IDL.Opt(IDL.Text),
  'assignedExecutiveId' : IDL.Opt(IDL.Principal),
  'perDayPrice' : IDL.Nat,
  'location' : Location,
  'photos' : IDL.Vec(ExternalBlob),
  'totalRooms' : IDL.Nat,
  'maxGuests' : IDL.Nat,
});
export const ServiceCategory = IDL.Variant({
  'setupKit' : IDL.Null,
  'other' : IDL.Null,
  'acCleaning' : IDL.Null,
  'homeCleaning' : IDL.Null,
});
export const ServiceInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : ServiceCategory,
  'price' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : ServiceCategory,
  'price' : IDL.Nat,
});
export const TaskType = IDL.Variant({
  'customerCheckin' : IDL.Null,
  'propertyVerification' : IDL.Null,
});
export const TaskInput = IDL.Record({
  'bookingId' : IDL.Opt(IDL.Nat),
  'propertyId' : IDL.Nat,
  'executiveId' : IDL.Principal,
  'taskType' : TaskType,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const VerificationTask = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'bookingId' : IDL.Opt(IDL.Nat),
  'createdAt' : IDL.Int,
  'propertyId' : IDL.Nat,
  'executiveId' : IDL.Principal,
  'taskType' : TaskType,
  'notes' : IDL.Opt(IDL.Text),
  'photos' : IDL.Vec(ExternalBlob),
});
export const AdminAnalytics = IDL.Record({
  'totalProperties' : IDL.Nat,
  'refundsProcessed' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'activeStays' : IDL.Nat,
  'pendingVerifications' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'owner' : IDL.Null,
  'executive' : IDL.Null,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'unverified' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'blacklisted' : IDL.Bool,
  'verificationStatus' : VerificationStatus,
});
export const NotificationType = IDL.Variant({
  'extendReminder' : IDL.Null,
  'paymentSuccess' : IDL.Null,
  'visitReminder' : IDL.Null,
  'bookingConfirmed' : IDL.Null,
  'docUploaded' : IDL.Null,
  'refundProcessed' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'notificationType' : NotificationType,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const OwnerEarnings = IDL.Record({
  'activeBookings' : IDL.Nat,
  'totalEarned' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'pendingPayout' : IDL.Nat,
});
export const PendingPayout = IDL.Record({
  'bookingId' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'releaseAt' : IDL.Int,
  'processed' : IDL.Bool,
  'amount' : IDL.Nat,
});
export const PropertyFilter = IDL.Record({
  'propertyType' : IDL.Opt(PropertyType),
  'city' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'tenantType' : IDL.Opt(TenantType),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const AvailabilityResult = IDL.Record({
  'available' : IDL.Bool,
  'nextAvailableFrom' : IDL.Opt(IDL.Int),
});
export const Rating = IDL.Record({
  'id' : IDL.Nat,
  'bookingId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'propertyId' : IDL.Nat,
  'reviewText' : IDL.Text,
  'customerId' : IDL.Principal,
  'rating' : IDL.Nat,
});
export const UserProfileInput = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const RatingInput = IDL.Record({
  'bookingId' : IDL.Nat,
  'propertyId' : IDL.Nat,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approveProperty' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignExecutive' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'blacklistUser' : IDL.Func([IDL.Principal], [], []),
  'createBooking' : IDL.Func([BookingInput], [Booking], []),
  'createDocument' : IDL.Func([DocumentInput], [Document], []),
  'createPayment' : IDL.Func([PaymentInput], [Payment], []),
  'createProperty' : IDL.Func([PropertyInput], [Property], []),
  'createService' : IDL.Func([ServiceInput], [Service], []),
  'createVerificationTask' : IDL.Func([TaskInput], [VerificationTask], []),
  'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
  'getAdminBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAdminPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAdminProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAdminUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getBookingDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getMyTasks' : IDL.Func([], [IDL.Vec(VerificationTask)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOwnerEarnings' : IDL.Func([], [OwnerEarnings], ['query']),
  'getPendingPayouts' : IDL.Func([], [IDL.Vec(PendingPayout)], ['query']),
  'getProperties' : IDL.Func(
      [IDL.Opt(PropertyFilter)],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'getPropertyAvailability' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Nat],
      [AvailabilityResult],
      ['query'],
    ),
  'getPropertyRatings' : IDL.Func([IDL.Nat], [IDL.Vec(Rating)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'markPayoutProcessed' : IDL.Func([IDL.Nat], [], []),
  'processDecision' : IDL.Func([IDL.Nat, DecisionStatus], [Booking], []),
  'rejectProperty' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
  'seedSampleBookings' : IDL.Func([IDL.Principal], [], ['oneway']),
  'submitRating' : IDL.Func([RatingInput], [Rating], []),
  'updateProperty' : IDL.Func(
      [IDL.Nat, PropertyInput],
      [IDL.Opt(Property)],
      [],
    ),
  'updateTaskStatus' : IDL.Func(
      [IDL.Nat, TaskStatus, IDL.Opt(IDL.Text)],
      [VerificationTask],
      [],
    ),
  'updateUserProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
  'uploadVerificationPhoto' : IDL.Func(
      [IDL.Nat, ExternalBlob],
      [VerificationTask],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingInput = IDL.Record({
    'checkIn' : IDL.Int,
    'totalDays' : IDL.Nat,
    'propertyId' : IDL.Nat,
    'serviceAddonIds' : IDL.Vec(IDL.Nat),
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const ServiceAddon = IDL.Record({
    'serviceName' : IDL.Text,
    'serviceId' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const DecisionStatus = IDL.Variant({
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'refunded' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'checkIn' : IDL.Int,
    'paymentStatus' : PaymentStatus,
    'decisionDeadline' : IDL.Int,
    'invoiceUrl' : IDL.Opt(IDL.Text),
    'serviceAddons' : IDL.Vec(ServiceAddon),
    'createdAt' : IDL.Int,
    'totalDays' : IDL.Nat,
    'propertyId' : IDL.Nat,
    'decisionStatus' : DecisionStatus,
    'checkOut' : IDL.Int,
    'customerId' : IDL.Principal,
    'totalPrice' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocType = IDL.Variant({
    'other' : IDL.Null,
    'passport' : IDL.Null,
    'aadhaar' : IDL.Null,
    'drivingLicense' : IDL.Null,
  });
  const UploadedBy = IDL.Variant({
    'customer' : IDL.Null,
    'executive' : IDL.Null,
  });
  const DocumentInput = IDL.Record({
    'bookingId' : IDL.Nat,
    'fileBlob' : ExternalBlob,
    'docType' : DocType,
    'uploadedBy' : UploadedBy,
  });
  const DocVerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'fileBlob' : ExternalBlob,
    'docType' : DocType,
    'verificationStatus' : DocVerificationStatus,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : UploadedBy,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'card' : IDL.Null,
    'wallet' : IDL.Null,
  });
  const PaymentInput = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'bookingId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'bookingId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'holdReleaseAt' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const PropertyType = IDL.Variant({
    'twoBHK' : IDL.Null,
    'oneRK' : IDL.Null,
    'room' : IDL.Null,
    'threeBHK' : IDL.Null,
    'oneBHK' : IDL.Null,
  });
  const FurnishingType = IDL.Variant({
    'semiFurnished' : IDL.Null,
    'furnished' : IDL.Null,
    'unfurnished' : IDL.Null,
  });
  const TenantType = IDL.Variant({
    'all' : IDL.Null,
    'boys' : IDL.Null,
    'girls' : IDL.Null,
    'family' : IDL.Null,
  });
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'city' : IDL.Text,
    'address' : IDL.Text,
  });
  const PropertyInput = IDL.Record({
    'propertyType' : PropertyType,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'furnishingType' : FurnishingType,
    'tenantType' : TenantType,
    'monthlyRent' : IDL.Nat,
    'roomsAvailable' : IDL.Nat,
    'location' : Location,
    'photos' : IDL.Vec(ExternalBlob),
    'totalRooms' : IDL.Nat,
    'maxGuests' : IDL.Nat,
  });
  const PropertyStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : PropertyStatus,
    'propertyType' : PropertyType,
    'ownerId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
    'furnishingType' : FurnishingType,
    'tenantType' : TenantType,
    'monthlyRent' : IDL.Nat,
    'roomsAvailable' : IDL.Nat,
    'verificationNotes' : IDL.Opt(IDL.Text),
    'assignedExecutiveId' : IDL.Opt(IDL.Principal),
    'perDayPrice' : IDL.Nat,
    'location' : Location,
    'photos' : IDL.Vec(ExternalBlob),
    'totalRooms' : IDL.Nat,
    'maxGuests' : IDL.Nat,
  });
  const ServiceCategory = IDL.Variant({
    'setupKit' : IDL.Null,
    'other' : IDL.Null,
    'acCleaning' : IDL.Null,
    'homeCleaning' : IDL.Null,
  });
  const ServiceInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : ServiceCategory,
    'price' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : ServiceCategory,
    'price' : IDL.Nat,
  });
  const TaskType = IDL.Variant({
    'customerCheckin' : IDL.Null,
    'propertyVerification' : IDL.Null,
  });
  const TaskInput = IDL.Record({
    'bookingId' : IDL.Opt(IDL.Nat),
    'propertyId' : IDL.Nat,
    'executiveId' : IDL.Principal,
    'taskType' : TaskType,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const VerificationTask = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'bookingId' : IDL.Opt(IDL.Nat),
    'createdAt' : IDL.Int,
    'propertyId' : IDL.Nat,
    'executiveId' : IDL.Principal,
    'taskType' : TaskType,
    'notes' : IDL.Opt(IDL.Text),
    'photos' : IDL.Vec(ExternalBlob),
  });
  const AdminAnalytics = IDL.Record({
    'totalProperties' : IDL.Nat,
    'refundsProcessed' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'activeStays' : IDL.Nat,
    'pendingVerifications' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'owner' : IDL.Null,
    'executive' : IDL.Null,
  });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'unverified' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'blacklisted' : IDL.Bool,
    'verificationStatus' : VerificationStatus,
  });
  const NotificationType = IDL.Variant({
    'extendReminder' : IDL.Null,
    'paymentSuccess' : IDL.Null,
    'visitReminder' : IDL.Null,
    'bookingConfirmed' : IDL.Null,
    'docUploaded' : IDL.Null,
    'refundProcessed' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'notificationType' : NotificationType,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const OwnerEarnings = IDL.Record({
    'activeBookings' : IDL.Nat,
    'totalEarned' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'pendingPayout' : IDL.Nat,
  });
  const PendingPayout = IDL.Record({
    'bookingId' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'releaseAt' : IDL.Int,
    'processed' : IDL.Bool,
    'amount' : IDL.Nat,
  });
  const PropertyFilter = IDL.Record({
    'propertyType' : IDL.Opt(PropertyType),
    'city' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'tenantType' : IDL.Opt(TenantType),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const AvailabilityResult = IDL.Record({
    'available' : IDL.Bool,
    'nextAvailableFrom' : IDL.Opt(IDL.Int),
  });
  const Rating = IDL.Record({
    'id' : IDL.Nat,
    'bookingId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'propertyId' : IDL.Nat,
    'reviewText' : IDL.Text,
    'customerId' : IDL.Principal,
    'rating' : IDL.Nat,
  });
  const UserProfileInput = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RatingInput = IDL.Record({
    'bookingId' : IDL.Nat,
    'propertyId' : IDL.Nat,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approveProperty' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignExecutive' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'blacklistUser' : IDL.Func([IDL.Principal], [], []),
    'createBooking' : IDL.Func([BookingInput], [Booking], []),
    'createDocument' : IDL.Func([DocumentInput], [Document], []),
    'createPayment' : IDL.Func([PaymentInput], [Payment], []),
    'createProperty' : IDL.Func([PropertyInput], [Property], []),
    'createService' : IDL.Func([ServiceInput], [Service], []),
    'createVerificationTask' : IDL.Func([TaskInput], [VerificationTask], []),
    'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
    'getAdminBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAdminPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAdminProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAdminUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getBookingDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getMyTasks' : IDL.Func([], [IDL.Vec(VerificationTask)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOwnerEarnings' : IDL.Func([], [OwnerEarnings], ['query']),
    'getPendingPayouts' : IDL.Func([], [IDL.Vec(PendingPayout)], ['query']),
    'getProperties' : IDL.Func(
        [IDL.Opt(PropertyFilter)],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
    'getPropertyAvailability' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Nat],
        [AvailabilityResult],
        ['query'],
      ),
    'getPropertyRatings' : IDL.Func([IDL.Nat], [IDL.Vec(Rating)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'markPayoutProcessed' : IDL.Func([IDL.Nat], [], []),
    'processDecision' : IDL.Func([IDL.Nat, DecisionStatus], [Booking], []),
    'rejectProperty' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
    'seedSampleBookings' : IDL.Func([IDL.Principal], [], ['oneway']),
    'submitRating' : IDL.Func([RatingInput], [Rating], []),
    'updateProperty' : IDL.Func(
        [IDL.Nat, PropertyInput],
        [IDL.Opt(Property)],
        [],
      ),
    'updateTaskStatus' : IDL.Func(
        [IDL.Nat, TaskStatus, IDL.Opt(IDL.Text)],
        [VerificationTask],
        [],
      ),
    'updateUserProfile' : IDL.Func([UserProfileInput], [UserProfile], []),
    'uploadVerificationPhoto' : IDL.Func(
        [IDL.Nat, ExternalBlob],
        [VerificationTask],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };