/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    lat: number;
    lng: number;
    city: string;
    address: string;
}
export interface Rating {
    id: bigint;
    bookingId: bigint;
    createdAt: bigint;
    propertyId: bigint;
    reviewText: string;
    customerId: Principal;
    rating: bigint;
}
export interface Document {
    id: bigint;
    bookingId: bigint;
    ownerId: Principal;
    fileBlob: ExternalBlob;
    docType: DocType;
    verificationStatus: DocVerificationStatus;
    uploadedAt: bigint;
    uploadedBy: UploadedBy;
}
export interface OwnerEarnings {
    activeBookings: bigint;
    totalEarned: bigint;
    totalBookings: bigint;
    pendingPayout: bigint;
}
export interface TaskInput {
    bookingId?: bigint;
    propertyId: bigint;
    executiveId: Principal;
    taskType: TaskType;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Property {
    id: bigint;
    status: PropertyStatus;
    propertyType: PropertyType;
    ownerId: Principal;
    createdAt: bigint;
    description: string;
    amenities: Array<string>;
    updatedAt: bigint;
    furnishingType: FurnishingType;
    tenantType: TenantType;
    monthlyRent: bigint;
    roomsAvailable: bigint;
    verificationNotes?: string;
    assignedExecutiveId?: Principal;
    perDayPrice: bigint;
    location: Location;
    photos: Array<ExternalBlob>;
    totalRooms: bigint;
    maxGuests: bigint;
}
export interface ServiceInput {
    name: string;
    description: string;
    category: ServiceCategory;
    price: bigint;
}
export interface DocumentInput {
    bookingId: bigint;
    fileBlob: ExternalBlob;
    docType: DocType;
    uploadedBy: UploadedBy;
}
export interface PaymentInput {
    paymentMethod: PaymentMethod;
    bookingId: bigint;
    amount: bigint;
}
export interface RatingInput {
    bookingId: bigint;
    propertyId: bigint;
    reviewText: string;
    rating: bigint;
}
export interface Booking {
    id: bigint;
    checkIn: bigint;
    paymentStatus: PaymentStatus;
    decisionDeadline: bigint;
    invoiceUrl?: string;
    serviceAddons: Array<ServiceAddon>;
    createdAt: bigint;
    totalDays: bigint;
    propertyId: bigint;
    decisionStatus: DecisionStatus;
    checkOut: bigint;
    customerId: Principal;
    totalPrice: bigint;
}
export interface AvailabilityResult {
    available: boolean;
    nextAvailableFrom?: bigint;
}
export interface PropertyFilter {
    propertyType?: PropertyType;
    city?: string;
    maxPrice?: bigint;
    tenantType?: TenantType;
    minPrice?: bigint;
}
export interface PendingPayout {
    bookingId: bigint;
    ownerId: Principal;
    releaseAt: bigint;
    processed: boolean;
    amount: bigint;
}
export interface BookingInput {
    checkIn: bigint;
    totalDays: bigint;
    propertyId: bigint;
    serviceAddonIds: Array<bigint>;
}
export interface AdminAnalytics {
    totalProperties: bigint;
    refundsProcessed: bigint;
    totalBookings: bigint;
    totalUsers: bigint;
    totalRevenue: bigint;
    activeStays: bigint;
    pendingVerifications: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Service {
    id: bigint;
    active: boolean;
    name: string;
    description: string;
    category: ServiceCategory;
    price: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Payment {
    id: bigint;
    status: PaymentStatus;
    paymentMethod: PaymentMethod;
    bookingId: bigint;
    createdAt: bigint;
    holdReleaseAt: bigint;
    amount: bigint;
}
export interface PropertyInput {
    propertyType: PropertyType;
    description: string;
    amenities: Array<string>;
    furnishingType: FurnishingType;
    tenantType: TenantType;
    monthlyRent: bigint;
    roomsAvailable: bigint;
    location: Location;
    photos: Array<ExternalBlob>;
    totalRooms: bigint;
    maxGuests: bigint;
}
export interface Notification {
    id: bigint;
    userId: Principal;
    notificationType: NotificationType;
    createdAt: bigint;
    read: boolean;
    message: string;
}
export interface VerificationTask {
    id: bigint;
    status: TaskStatus;
    completedAt?: bigint;
    bookingId?: bigint;
    createdAt: bigint;
    propertyId: bigint;
    executiveId: Principal;
    taskType: TaskType;
    notes?: string;
    photos: Array<ExternalBlob>;
}
export interface UserProfileInput {
    name: string;
    role: UserRole;
    email: string;
    phone: string;
}
export interface ServiceAddon {
    serviceName: string;
    serviceId: bigint;
    price: bigint;
}
export interface UserProfile {
    id: Principal;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
    phone: string;
    blacklisted: boolean;
    verificationStatus: VerificationStatus;
}
export enum DecisionStatus {
    expired = "expired",
    pending = "pending",
    refunded = "refunded",
    accepted = "accepted"
}
export enum DocType {
    other = "other",
    passport = "passport",
    aadhaar = "aadhaar",
    drivingLicense = "drivingLicense"
}
export enum DocVerificationStatus {
    verified = "verified",
    pending = "pending",
    rejected = "rejected"
}
export enum FurnishingType {
    semiFurnished = "semiFurnished",
    furnished = "furnished",
    unfurnished = "unfurnished"
}
export enum NotificationType {
    extendReminder = "extendReminder",
    paymentSuccess = "paymentSuccess",
    visitReminder = "visitReminder",
    bookingConfirmed = "bookingConfirmed",
    docUploaded = "docUploaded",
    refundProcessed = "refundProcessed"
}
export enum PaymentMethod {
    upi = "upi",
    card = "card",
    wallet = "wallet"
}
export enum PaymentStatus {
    pending = "pending",
    success = "success",
    failed = "failed"
}
export enum PropertyStatus {
    assigned = "assigned",
    verified = "verified",
    pending = "pending",
    rejected = "rejected"
}
export enum PropertyType {
    twoBHK = "twoBHK",
    oneRK = "oneRK",
    room = "room",
    threeBHK = "threeBHK",
    oneBHK = "oneBHK"
}
export enum ServiceCategory {
    setupKit = "setupKit",
    other = "other",
    acCleaning = "acCleaning",
    homeCleaning = "homeCleaning"
}
export enum TaskStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum TaskType {
    customerCheckin = "customerCheckin",
    propertyVerification = "propertyVerification"
}
export enum TenantType {
    all = "all",
    boys = "boys",
    girls = "girls",
    family = "family"
}
export enum UploadedBy {
    customer = "customer",
    executive = "executive"
}
export enum UserRole {
    admin = "admin",
    customer = "customer",
    owner = "owner",
    executive = "executive"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VerificationStatus {
    verified = "verified",
    pending = "pending",
    unverified = "unverified",
    rejected = "rejected"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    approveProperty(propertyId: bigint, notes: string | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignExecutive(propertyId: bigint, executiveId: Principal): Promise<void>;
    blacklistUser(userId: Principal): Promise<void>;
    createBooking(input: BookingInput): Promise<Booking>;
    createDocument(input: DocumentInput): Promise<Document>;
    createPayment(input: PaymentInput): Promise<Payment>;
    createProperty(input: PropertyInput): Promise<Property>;
    createService(input: ServiceInput): Promise<Service>;
    createVerificationTask(input: TaskInput): Promise<VerificationTask>;
    getAdminAnalytics(): Promise<AdminAnalytics>;
    getAdminBookings(): Promise<Array<Booking>>;
    getAdminPayments(): Promise<Array<Payment>>;
    getAdminProperties(): Promise<Array<Property>>;
    getAdminUsers(): Promise<Array<UserProfile>>;
    getBooking(bookingId: bigint): Promise<Booking | null>;
    getBookingDocuments(bookingId: bigint): Promise<Array<Document>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getMyBookings(): Promise<Array<Booking>>;
    getMyPayments(): Promise<Array<Payment>>;
    getMyTasks(): Promise<Array<VerificationTask>>;
    getNotifications(): Promise<Array<Notification>>;
    getOwnerEarnings(): Promise<OwnerEarnings>;
    getPendingPayouts(): Promise<Array<PendingPayout>>;
    getProperties(filter: PropertyFilter | null): Promise<Array<Property>>;
    getProperty(propertyId: bigint): Promise<Property | null>;
    getPropertyAvailability(propertyId: bigint, checkIn: bigint, totalDays: bigint): Promise<AvailabilityResult>;
    getPropertyRatings(propertyId: bigint): Promise<Array<Rating>>;
    getServices(): Promise<Array<Service>>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationRead(notificationId: bigint): Promise<void>;
    markPayoutProcessed(bookingId: bigint): Promise<void>;
    processDecision(bookingId: bigint, decision: DecisionStatus): Promise<Booking>;
    rejectProperty(propertyId: bigint, notes: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfileInput): Promise<void>;
    seedSampleBookings(sampleCustomerId: Principal): Promise<void>;
    submitRating(input: RatingInput): Promise<Rating>;
    updateProperty(propertyId: bigint, input: PropertyInput): Promise<Property | null>;
    updateTaskStatus(taskId: bigint, status: TaskStatus, notes: string | null): Promise<VerificationTask>;
    updateUserProfile(input: UserProfileInput): Promise<UserProfile>;
    uploadVerificationPhoto(taskId: bigint, photo: ExternalBlob): Promise<VerificationTask>;
}
import type { AvailabilityResult as _AvailabilityResult, Booking as _Booking, DecisionStatus as _DecisionStatus, DocType as _DocType, DocVerificationStatus as _DocVerificationStatus, Document as _Document, DocumentInput as _DocumentInput, ExternalBlob as _ExternalBlob, FurnishingType as _FurnishingType, Location as _Location, Notification as _Notification, NotificationType as _NotificationType, Payment as _Payment, PaymentInput as _PaymentInput, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, Property as _Property, PropertyFilter as _PropertyFilter, PropertyInput as _PropertyInput, PropertyStatus as _PropertyStatus, PropertyType as _PropertyType, Service as _Service, ServiceAddon as _ServiceAddon, ServiceCategory as _ServiceCategory, ServiceInput as _ServiceInput, TaskInput as _TaskInput, TaskStatus as _TaskStatus, TaskType as _TaskType, TenantType as _TenantType, UploadedBy as _UploadedBy, UserProfile as _UserProfile, UserProfileInput as _UserProfileInput, UserRole as _UserRole, UserRole__1 as _UserRole__1, VerificationStatus as _VerificationStatus, VerificationTask as _VerificationTask, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async approveProperty(arg0: bigint, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveProperty(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveProperty(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignExecutive(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignExecutive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignExecutive(arg0, arg1);
            return result;
        }
    }
    async blacklistUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blacklistUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blacklistUser(arg0);
            return result;
        }
    }
    async createBooking(arg0: BookingInput): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return from_candid_Booking_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return from_candid_Booking_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDocument(arg0: DocumentInput): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(await to_candid_DocumentInput_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Document_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(await to_candid_DocumentInput_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Document_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPayment(arg0: PaymentInput): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(to_candid_PaymentInput_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Payment_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(to_candid_PaymentInput_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Payment_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProperty(arg0: PropertyInput): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.createProperty(await to_candid_PropertyInput_n42(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Property_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProperty(await to_candid_PropertyInput_n42(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Property_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async createService(arg0: ServiceInput): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(to_candid_ServiceInput_n63(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Service_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(to_candid_ServiceInput_n63(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Service_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async createVerificationTask(arg0: TaskInput): Promise<VerificationTask> {
        if (this.processError) {
            try {
                const result = await this.actor.createVerificationTask(to_candid_TaskInput_n71(this._uploadFile, this._downloadFile, arg0));
                return from_candid_VerificationTask_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVerificationTask(to_candid_TaskInput_n71(this._uploadFile, this._downloadFile, arg0));
            return from_candid_VerificationTask_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminAnalytics(): Promise<AdminAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAnalytics();
            return result;
        }
    }
    async getAdminBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminBookings();
                return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminBookings();
            return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPayments();
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPayments();
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminProperties();
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminProperties();
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUsers();
                return from_candid_vec_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUsers();
            return from_candid_vec_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: bigint): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n92(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n92(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingDocuments(arg0: bigint): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingDocuments(arg0);
                return from_candid_vec_n93(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingDocuments(arg0);
            return from_candid_vec_n93(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n94(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n94(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n95(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n95(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPayments();
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPayments();
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTasks(): Promise<Array<VerificationTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTasks();
                return from_candid_vec_n97(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTasks();
            return from_candid_vec_n97(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n98(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n98(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerEarnings(): Promise<OwnerEarnings> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerEarnings();
            return result;
        }
    }
    async getPendingPayouts(): Promise<Array<PendingPayout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPayouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPayouts();
            return result;
        }
    }
    async getProperties(arg0: PropertyFilter | null): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperties(to_candid_opt_n103(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperties(to_candid_opt_n103(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: bigint): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n106(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n106(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertyAvailability(arg0: bigint, arg1: bigint, arg2: bigint): Promise<AvailabilityResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyAvailability(arg0, arg1, arg2);
                return from_candid_AvailabilityResult_n107(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyAvailability(arg0, arg1, arg2);
            return from_candid_AvailabilityResult_n107(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertyRatings(arg0: bigint): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyRatings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyRatings(arg0);
            return result;
        }
    }
    async getServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return from_candid_vec_n109(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return from_candid_vec_n109(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n94(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n94(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async markPayoutProcessed(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPayoutProcessed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPayoutProcessed(arg0);
            return result;
        }
    }
    async processDecision(arg0: bigint, arg1: DecisionStatus): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.processDecision(arg0, to_candid_DecisionStatus_n110(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Booking_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processDecision(arg0, to_candid_DecisionStatus_n110(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Booking_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectProperty(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectProperty(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectProperty(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n112(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n112(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedSampleBookings(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleBookings(arg0);
            return result;
        }
    }
    async submitRating(arg0: RatingInput): Promise<Rating> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(arg0);
            return result;
        }
    }
    async updateProperty(arg0: bigint, arg1: PropertyInput): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, await to_candid_PropertyInput_n42(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n106(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, await to_candid_PropertyInput_n42(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n106(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTaskStatus(arg0: bigint, arg1: TaskStatus, arg2: string | null): Promise<VerificationTask> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n116(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_VerificationTask_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n116(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_VerificationTask_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: UserProfileInput): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfileInput_n112(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n86(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfileInput_n112(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n86(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadVerificationPhoto(arg0: bigint, arg1: ExternalBlob): Promise<VerificationTask> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVerificationPhoto(arg0, await to_candid_ExternalBlob_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_VerificationTask_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVerificationPhoto(arg0, await to_candid_ExternalBlob_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_VerificationTask_n75(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AvailabilityResult_n107(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailabilityResult): AvailabilityResult {
    return from_candid_record_n108(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_DecisionStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DecisionStatus): DecisionStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_DocType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocType): DocType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_DocVerificationStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocVerificationStatus): DocVerificationStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FurnishingType_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FurnishingType): FurnishingType {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n102(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n100(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyStatus): PropertyStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
async function from_candid_Property_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Promise<Property> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function from_candid_TenantType_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TenantType): TenantType {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_UploadedBy_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadedBy): UploadedBy {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n87(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n96(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n91(_uploadFile, _downloadFile, value);
}
async function from_candid_VerificationTask_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationTask): Promise<VerificationTask> {
    return await from_candid_record_n76(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n106(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Promise<Property | null> {
    return value.length === 0 ? null : await from_candid_Property_n51(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n86(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: Principal;
    notificationType: _NotificationType;
    createdAt: bigint;
    read: boolean;
    message: string;
}): {
    id: bigint;
    userId: Principal;
    notificationType: NotificationType;
    createdAt: bigint;
    read: boolean;
    message: string;
} {
    return {
        id: value.id,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n101(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        read: value.read,
        message: value.message
    };
}
function from_candid_record_n108(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    available: boolean;
    nextAvailableFrom: [] | [bigint];
}): {
    available: boolean;
    nextAvailableFrom?: bigint;
} {
    return {
        available: value.available,
        nextAvailableFrom: record_opt_to_undefined(from_candid_opt_n79(_uploadFile, _downloadFile, value.nextAvailableFrom))
    };
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    checkIn: bigint;
    paymentStatus: _PaymentStatus;
    decisionDeadline: bigint;
    invoiceUrl: [] | [string];
    serviceAddons: Array<_ServiceAddon>;
    createdAt: bigint;
    totalDays: bigint;
    propertyId: bigint;
    decisionStatus: _DecisionStatus;
    checkOut: bigint;
    customerId: Principal;
    totalPrice: bigint;
}): {
    id: bigint;
    checkIn: bigint;
    paymentStatus: PaymentStatus;
    decisionDeadline: bigint;
    invoiceUrl?: string;
    serviceAddons: Array<ServiceAddon>;
    createdAt: bigint;
    totalDays: bigint;
    propertyId: bigint;
    decisionStatus: DecisionStatus;
    checkOut: bigint;
    customerId: Principal;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        checkIn: value.checkIn,
        paymentStatus: from_candid_PaymentStatus_n13(_uploadFile, _downloadFile, value.paymentStatus),
        decisionDeadline: value.decisionDeadline,
        invoiceUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.invoiceUrl)),
        serviceAddons: value.serviceAddons,
        createdAt: value.createdAt,
        totalDays: value.totalDays,
        propertyId: value.propertyId,
        decisionStatus: from_candid_DecisionStatus_n16(_uploadFile, _downloadFile, value.decisionStatus),
        checkOut: value.checkOut,
        customerId: value.customerId,
        totalPrice: value.totalPrice
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bookingId: bigint;
    ownerId: Principal;
    fileBlob: _ExternalBlob;
    docType: _DocType;
    verificationStatus: _DocVerificationStatus;
    uploadedAt: bigint;
    uploadedBy: _UploadedBy;
}): Promise<{
    id: bigint;
    bookingId: bigint;
    ownerId: Principal;
    fileBlob: ExternalBlob;
    docType: DocType;
    verificationStatus: DocVerificationStatus;
    uploadedAt: bigint;
    uploadedBy: UploadedBy;
}> {
    return {
        id: value.id,
        bookingId: value.bookingId,
        ownerId: value.ownerId,
        fileBlob: await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value.fileBlob),
        docType: from_candid_DocType_n28(_uploadFile, _downloadFile, value.docType),
        verificationStatus: from_candid_DocVerificationStatus_n30(_uploadFile, _downloadFile, value.verificationStatus),
        uploadedAt: value.uploadedAt,
        uploadedBy: from_candid_UploadedBy_n32(_uploadFile, _downloadFile, value.uploadedBy)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    paymentMethod: _PaymentMethod;
    bookingId: bigint;
    createdAt: bigint;
    holdReleaseAt: bigint;
    amount: bigint;
}): {
    id: bigint;
    status: PaymentStatus;
    paymentMethod: PaymentMethod;
    bookingId: bigint;
    createdAt: bigint;
    holdReleaseAt: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n13(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n40(_uploadFile, _downloadFile, value.paymentMethod),
        bookingId: value.bookingId,
        createdAt: value.createdAt,
        holdReleaseAt: value.holdReleaseAt,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PropertyStatus;
    propertyType: _PropertyType;
    ownerId: Principal;
    createdAt: bigint;
    description: string;
    amenities: Array<string>;
    updatedAt: bigint;
    furnishingType: _FurnishingType;
    tenantType: _TenantType;
    monthlyRent: bigint;
    roomsAvailable: bigint;
    verificationNotes: [] | [string];
    assignedExecutiveId: [] | [Principal];
    perDayPrice: bigint;
    location: _Location;
    photos: Array<_ExternalBlob>;
    totalRooms: bigint;
    maxGuests: bigint;
}): Promise<{
    id: bigint;
    status: PropertyStatus;
    propertyType: PropertyType;
    ownerId: Principal;
    createdAt: bigint;
    description: string;
    amenities: Array<string>;
    updatedAt: bigint;
    furnishingType: FurnishingType;
    tenantType: TenantType;
    monthlyRent: bigint;
    roomsAvailable: bigint;
    verificationNotes?: string;
    assignedExecutiveId?: Principal;
    perDayPrice: bigint;
    location: Location;
    photos: Array<ExternalBlob>;
    totalRooms: bigint;
    maxGuests: bigint;
}> {
    return {
        id: value.id,
        status: from_candid_PropertyStatus_n53(_uploadFile, _downloadFile, value.status),
        propertyType: from_candid_PropertyType_n55(_uploadFile, _downloadFile, value.propertyType),
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        description: value.description,
        amenities: value.amenities,
        updatedAt: value.updatedAt,
        furnishingType: from_candid_FurnishingType_n57(_uploadFile, _downloadFile, value.furnishingType),
        tenantType: from_candid_TenantType_n59(_uploadFile, _downloadFile, value.tenantType),
        monthlyRent: value.monthlyRent,
        roomsAvailable: value.roomsAvailable,
        verificationNotes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.verificationNotes)),
        assignedExecutiveId: record_opt_to_undefined(from_candid_opt_n61(_uploadFile, _downloadFile, value.assignedExecutiveId)),
        perDayPrice: value.perDayPrice,
        location: value.location,
        photos: await from_candid_vec_n62(_uploadFile, _downloadFile, value.photos),
        totalRooms: value.totalRooms,
        maxGuests: value.maxGuests
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    name: string;
    description: string;
    category: _ServiceCategory;
    price: bigint;
}): {
    id: bigint;
    active: boolean;
    name: string;
    description: string;
    category: ServiceCategory;
    price: bigint;
} {
    return {
        id: value.id,
        active: value.active,
        name: value.name,
        description: value.description,
        category: from_candid_ServiceCategory_n69(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
async function from_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    completedAt: [] | [bigint];
    bookingId: [] | [bigint];
    createdAt: bigint;
    propertyId: bigint;
    executiveId: Principal;
    taskType: _TaskType;
    notes: [] | [string];
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    status: TaskStatus;
    completedAt?: bigint;
    bookingId?: bigint;
    createdAt: bigint;
    propertyId: bigint;
    executiveId: Principal;
    taskType: TaskType;
    notes?: string;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n77(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n79(_uploadFile, _downloadFile, value.completedAt)),
        bookingId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bookingId)),
        createdAt: value.createdAt,
        propertyId: value.propertyId,
        executiveId: value.executiveId,
        taskType: from_candid_TaskType_n80(_uploadFile, _downloadFile, value.taskType),
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        photos: await from_candid_vec_n62(_uploadFile, _downloadFile, value.photos)
    };
}
function from_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    createdAt: bigint;
    role: _UserRole;
    email: string;
    phone: string;
    blacklisted: boolean;
    verificationStatus: _VerificationStatus;
}): {
    id: Principal;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
    phone: string;
    blacklisted: boolean;
    verificationStatus: VerificationStatus;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n88(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        blacklisted: value.blacklisted,
        verificationStatus: from_candid_VerificationStatus_n90(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
function from_candid_variant_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    extendReminder: null;
} | {
    paymentSuccess: null;
} | {
    visitReminder: null;
} | {
    bookingConfirmed: null;
} | {
    docUploaded: null;
} | {
    refundProcessed: null;
}): NotificationType {
    return "extendReminder" in value ? NotificationType.extendReminder : "paymentSuccess" in value ? NotificationType.paymentSuccess : "visitReminder" in value ? NotificationType.visitReminder : "bookingConfirmed" in value ? NotificationType.bookingConfirmed : "docUploaded" in value ? NotificationType.docUploaded : "refundProcessed" in value ? NotificationType.refundProcessed : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    success: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "success" in value ? PaymentStatus.success : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expired: null;
} | {
    pending: null;
} | {
    refunded: null;
} | {
    accepted: null;
}): DecisionStatus {
    return "expired" in value ? DecisionStatus.expired : "pending" in value ? DecisionStatus.pending : "refunded" in value ? DecisionStatus.refunded : "accepted" in value ? DecisionStatus.accepted : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    passport: null;
} | {
    aadhaar: null;
} | {
    drivingLicense: null;
}): DocType {
    return "other" in value ? DocType.other : "passport" in value ? DocType.passport : "aadhaar" in value ? DocType.aadhaar : "drivingLicense" in value ? DocType.drivingLicense : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
}): DocVerificationStatus {
    return "verified" in value ? DocVerificationStatus.verified : "pending" in value ? DocVerificationStatus.pending : "rejected" in value ? DocVerificationStatus.rejected : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    executive: null;
}): UploadedBy {
    return "customer" in value ? UploadedBy.customer : "executive" in value ? UploadedBy.executive : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    card: null;
} | {
    wallet: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "card" in value ? PaymentMethod.card : "wallet" in value ? PaymentMethod.wallet : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
}): PropertyStatus {
    return "assigned" in value ? PropertyStatus.assigned : "verified" in value ? PropertyStatus.verified : "pending" in value ? PropertyStatus.pending : "rejected" in value ? PropertyStatus.rejected : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twoBHK: null;
} | {
    oneRK: null;
} | {
    room: null;
} | {
    threeBHK: null;
} | {
    oneBHK: null;
}): PropertyType {
    return "twoBHK" in value ? PropertyType.twoBHK : "oneRK" in value ? PropertyType.oneRK : "room" in value ? PropertyType.room : "threeBHK" in value ? PropertyType.threeBHK : "oneBHK" in value ? PropertyType.oneBHK : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    semiFurnished: null;
} | {
    furnished: null;
} | {
    unfurnished: null;
}): FurnishingType {
    return "semiFurnished" in value ? FurnishingType.semiFurnished : "furnished" in value ? FurnishingType.furnished : "unfurnished" in value ? FurnishingType.unfurnished : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    boys: null;
} | {
    girls: null;
} | {
    family: null;
}): TenantType {
    return "all" in value ? TenantType.all : "boys" in value ? TenantType.boys : "girls" in value ? TenantType.girls : "family" in value ? TenantType.family : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    setupKit: null;
} | {
    other: null;
} | {
    acCleaning: null;
} | {
    homeCleaning: null;
}): ServiceCategory {
    return "setupKit" in value ? ServiceCategory.setupKit : "other" in value ? ServiceCategory.other : "acCleaning" in value ? ServiceCategory.acCleaning : "homeCleaning" in value ? ServiceCategory.homeCleaning : value;
}
function from_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerCheckin: null;
} | {
    propertyVerification: null;
}): TaskType {
    return "customerCheckin" in value ? TaskType.customerCheckin : "propertyVerification" in value ? TaskType.propertyVerification : value;
}
function from_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    owner: null;
} | {
    executive: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "customer" in value ? UserRole.customer : "owner" in value ? UserRole.owner : "executive" in value ? UserRole.executive : value;
}
function from_candid_variant_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    unverified: null;
} | {
    rejected: null;
}): VerificationStatus {
    return "verified" in value ? VerificationStatus.verified : "pending" in value ? VerificationStatus.pending : "unverified" in value ? VerificationStatus.unverified : "rejected" in value ? VerificationStatus.rejected : value;
}
function from_candid_variant_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n109(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n67(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n38(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Promise<Array<Property>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Property_n51(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n86(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Promise<Array<Document>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Document_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VerificationTask>): Promise<Array<VerificationTask>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VerificationTask_n75(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n99(_uploadFile, _downloadFile, x));
}
function to_candid_DecisionStatus_n110(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DecisionStatus): _DecisionStatus {
    return to_candid_variant_n111(_uploadFile, _downloadFile, value);
}
function to_candid_DocType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocType): _DocType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_DocumentInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentInput): Promise<_DocumentInput> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FurnishingType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FurnishingType): _FurnishingType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentInput_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentInput): _PaymentInput {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyFilter_n104(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyFilter): _PropertyFilter {
    return to_candid_record_n105(_uploadFile, _downloadFile, value);
}
async function to_candid_PropertyInput_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyInput): Promise<_PropertyInput> {
    return await to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceInput_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceInput): _ServiceInput {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_TaskInput_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskInput): _TaskInput {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n116(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n117(_uploadFile, _downloadFile, value);
}
function to_candid_TaskType_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_TenantType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TenantType): _TenantType {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UploadedBy_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UploadedBy): _UploadedBy {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfileInput_n112(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileInput): _UserProfileInput {
    return to_candid_record_n113(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n114(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n115(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n103(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyFilter | null): [] | [_PropertyFilter] {
    return value === null ? candid_none() : candid_some(to_candid_PropertyFilter_n104(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n105(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyType?: PropertyType;
    city?: string;
    maxPrice?: bigint;
    tenantType?: TenantType;
    minPrice?: bigint;
}): {
    propertyType: [] | [_PropertyType];
    city: [] | [string];
    maxPrice: [] | [bigint];
    tenantType: [] | [_TenantType];
    minPrice: [] | [bigint];
} {
    return {
        propertyType: value.propertyType ? candid_some(to_candid_PropertyType_n44(_uploadFile, _downloadFile, value.propertyType)) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        tenantType: value.tenantType ? candid_some(to_candid_TenantType_n48(_uploadFile, _downloadFile, value.tenantType)) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_record_n113(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
    email: string;
    phone: string;
}): {
    name: string;
    role: _UserRole;
    email: string;
    phone: string;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n114(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bookingId: bigint;
    fileBlob: ExternalBlob;
    docType: DocType;
    uploadedBy: UploadedBy;
}): Promise<{
    bookingId: bigint;
    fileBlob: _ExternalBlob;
    docType: _DocType;
    uploadedBy: _UploadedBy;
}> {
    return {
        bookingId: value.bookingId,
        fileBlob: await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.fileBlob),
        docType: to_candid_DocType_n21(_uploadFile, _downloadFile, value.docType),
        uploadedBy: to_candid_UploadedBy_n23(_uploadFile, _downloadFile, value.uploadedBy)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    bookingId: bigint;
    amount: bigint;
}): {
    paymentMethod: _PaymentMethod;
    bookingId: bigint;
    amount: bigint;
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n36(_uploadFile, _downloadFile, value.paymentMethod),
        bookingId: value.bookingId,
        amount: value.amount
    };
}
async function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyType: PropertyType;
    description: string;
    amenities: Array<string>;
    furnishingType: FurnishingType;
    tenantType: TenantType;
    monthlyRent: bigint;
    roomsAvailable: bigint;
    location: Location;
    photos: Array<ExternalBlob>;
    totalRooms: bigint;
    maxGuests: bigint;
}): Promise<{
    propertyType: _PropertyType;
    description: string;
    amenities: Array<string>;
    furnishingType: _FurnishingType;
    tenantType: _TenantType;
    monthlyRent: bigint;
    roomsAvailable: bigint;
    location: _Location;
    photos: Array<_ExternalBlob>;
    totalRooms: bigint;
    maxGuests: bigint;
}> {
    return {
        propertyType: to_candid_PropertyType_n44(_uploadFile, _downloadFile, value.propertyType),
        description: value.description,
        amenities: value.amenities,
        furnishingType: to_candid_FurnishingType_n46(_uploadFile, _downloadFile, value.furnishingType),
        tenantType: to_candid_TenantType_n48(_uploadFile, _downloadFile, value.tenantType),
        monthlyRent: value.monthlyRent,
        roomsAvailable: value.roomsAvailable,
        location: value.location,
        photos: await to_candid_vec_n50(_uploadFile, _downloadFile, value.photos),
        totalRooms: value.totalRooms,
        maxGuests: value.maxGuests
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    category: ServiceCategory;
    price: bigint;
}): {
    name: string;
    description: string;
    category: _ServiceCategory;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        category: to_candid_ServiceCategory_n65(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bookingId?: bigint;
    propertyId: bigint;
    executiveId: Principal;
    taskType: TaskType;
}): {
    bookingId: [] | [bigint];
    propertyId: bigint;
    executiveId: Principal;
    taskType: _TaskType;
} {
    return {
        bookingId: value.bookingId ? candid_some(value.bookingId) : candid_none(),
        propertyId: value.propertyId,
        executiveId: value.executiveId,
        taskType: to_candid_TaskType_n73(_uploadFile, _downloadFile, value.taskType)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n111(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DecisionStatus): {
    expired: null;
} | {
    pending: null;
} | {
    refunded: null;
} | {
    accepted: null;
} {
    return value == DecisionStatus.expired ? {
        expired: null
    } : value == DecisionStatus.pending ? {
        pending: null
    } : value == DecisionStatus.refunded ? {
        refunded: null
    } : value == DecisionStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n115(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    customer: null;
} | {
    owner: null;
} | {
    executive: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.customer ? {
        customer: null
    } : value == UserRole.owner ? {
        owner: null
    } : value == UserRole.executive ? {
        executive: null
    } : value;
}
function to_candid_variant_n117(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.pending ? {
        pending: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocType): {
    other: null;
} | {
    passport: null;
} | {
    aadhaar: null;
} | {
    drivingLicense: null;
} {
    return value == DocType.other ? {
        other: null
    } : value == DocType.passport ? {
        passport: null
    } : value == DocType.aadhaar ? {
        aadhaar: null
    } : value == DocType.drivingLicense ? {
        drivingLicense: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UploadedBy): {
    customer: null;
} | {
    executive: null;
} {
    return value == UploadedBy.customer ? {
        customer: null
    } : value == UploadedBy.executive ? {
        executive: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    card: null;
} | {
    wallet: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.card ? {
        card: null
    } : value == PaymentMethod.wallet ? {
        wallet: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    twoBHK: null;
} | {
    oneRK: null;
} | {
    room: null;
} | {
    threeBHK: null;
} | {
    oneBHK: null;
} {
    return value == PropertyType.twoBHK ? {
        twoBHK: null
    } : value == PropertyType.oneRK ? {
        oneRK: null
    } : value == PropertyType.room ? {
        room: null
    } : value == PropertyType.threeBHK ? {
        threeBHK: null
    } : value == PropertyType.oneBHK ? {
        oneBHK: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FurnishingType): {
    semiFurnished: null;
} | {
    furnished: null;
} | {
    unfurnished: null;
} {
    return value == FurnishingType.semiFurnished ? {
        semiFurnished: null
    } : value == FurnishingType.furnished ? {
        furnished: null
    } : value == FurnishingType.unfurnished ? {
        unfurnished: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TenantType): {
    all: null;
} | {
    boys: null;
} | {
    girls: null;
} | {
    family: null;
} {
    return value == TenantType.all ? {
        all: null
    } : value == TenantType.boys ? {
        boys: null
    } : value == TenantType.girls ? {
        girls: null
    } : value == TenantType.family ? {
        family: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    setupKit: null;
} | {
    other: null;
} | {
    acCleaning: null;
} | {
    homeCleaning: null;
} {
    return value == ServiceCategory.setupKit ? {
        setupKit: null
    } : value == ServiceCategory.other ? {
        other: null
    } : value == ServiceCategory.acCleaning ? {
        acCleaning: null
    } : value == ServiceCategory.homeCleaning ? {
        homeCleaning: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    customerCheckin: null;
} | {
    propertyVerification: null;
} {
    return value == TaskType.customerCheckin ? {
        customerCheckin: null
    } : value == TaskType.propertyVerification ? {
        propertyVerification: null
    } : value;
}
async function to_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
